version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
  backend:
    volumes:
      - ./:/var/www/html
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    depends_on:
      - mysql
    container_name: laravel

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    ports:
      - 3307:3306
    volumes:
      - davesql:/var/lib/mysql

volumes:
  davesql:
  laravel-server:
